### ISSUE TITLE
Use a fixed port for NGINX and APIGATEWAY

### ISSUE THREAD

**Issue by daisy-ycguo** [xingzhou/Deploy_OpenWhisk_with_Helm#9]
I hope to use a fixed port to access NGINX.
Also, APIGATEWAY needs a fixed port to access externally.

**Comment by xingzhou** [comment]
Done, please take a look a the latest master code. By default, nginx HTTP port is at 30000, HTTPS is at 30001, HTTPS admin is at 30002
